version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.bot
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
