version: "3.8"
services:
  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
  bot:
    build:
      context: ./bot
    command: python main.py
    environment:
      - TELEGRAM_BOT_TOKEN=your-telegram-bot-token
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
