services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      TELEGRAM_TOKEN: "7586067879:AAFtBcPcu8_eQYVmUqmpDltASX7TLZObwkI"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
