# Base Image
FROM python:3.9-slim

# Set Working Directory
WORKDIR /app

# Install Dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy Application Files
COPY . .

# Expose Port
EXPOSE 5000

# Run Application
CMD ["python", "app.py"]
